In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Creating my own data set
my_df = pd.DataFrame(np.random.rand(20, 10), columns=['A','B','C','D','E','F','G','H','I','J'])
print (my_df)

           A         B         C         D         E         F         G  \
0   0.707222  0.209537  0.743903  0.312564  0.317582  0.839395  0.203450
1   0.391954  0.212021  0.097478  0.436357  0.896519  0.084124  0.327129
2   0.802437  0.450996  0.827864  0.509012  0.583503  0.745038  0.701361
3   0.021493  0.134411  0.599459  0.166666  0.335143  0.734784  0.135807
4   0.465178  0.301218  0.458839  0.384578  0.093338  0.716674  0.556082
5   0.222073  0.761487  0.578925  0.964957  0.330813  0.684612  0.792796
6   0.435038  0.325918  0.120039  0.161330  0.478793  0.886857  0.185711
7   0.442192  0.375204  0.757648  0.326607  0.904102  0.325879  0.902556
8   0.107672  0.675172  0.827526  0.535407  0.843109  0.164080  0.137897
9   0.165782  0.450213  0.381301  0.514679  0.285570  0.052622  0.977441
10  0.289834  0.887638  0.400126  0.987744  0.119054  0.200867  0.576161
11  0.714904  0.327524  0.621200  0.699448  0.651104  0.346227  0.828027
12  0.300957  0.148028  0.777524  0.285748  0.969536  0.478227  0.788575
13  0.317026  0.872600  0.052407  0.578974  0.816885  0.277451  0.805257
14  0.140518  0.028889  0.227621  0.553861  0.778982  0.647294  0.450307
15  0.326433  0.721598  0.197161  0.280958  0.129487  0.566434  0.197363
16  0.974002  0.800269  0.349325  0.680640  0.704014  0.688224  0.096507
17  0.531291  0.646011  0.224935  0.556918  0.638876  0.286673  0.135122
18  0.340485  0.678213  0.127507  0.329841  0.206992  0.988797  0.164046
19  0.852272  0.179733  0.103616  0.215751  0.224524  0.873787  0.381192

           H         I         J
0   0.068030  0.428029  0.683061
1   0.989000  0.627265  0.571786
2   0.110426  0.582781  0.972909
3   0.739456  0.396419  0.492639
4   0.465797  0.848366  0.105578
5   0.045593  0.377283  0.993565
6   0.168993  0.780361  0.675461
7   0.349280  0.627164  0.170552
8   0.909336  0.045789  0.098126
9   0.971716  0.052274  0.591113
10  0.541849  0.764880  0.375509
11  0.141015  0.400161  0.431028
12  0.380996  0.222346  0.405423
13  0.090490  0.471909  0.872151
14  0.443682  0.784809  0.027299
15  0.829995  0.481920  0.948330
16  0.701001  0.015671  0.135187
17  0.395571  0.062288  0.967818
18  0.670521  0.005501  0.116798
19  0.439630  0.023006  0.110805

In [4]:
# Display top few values
my_df.head()

,A,B,C,D,E,F,G,H,I,J
0,0.707222,0.209537,0.743903,0.312564,0.317582,0.839395,0.203450,0.068030,0.428029,0.683061
1,0.391954,0.212021,0.097478,0.436357,0.896519,0.084124,0.327129,0.989000,0.627265,0.571786
2,0.802437,0.450996,0.827864,0.509012,0.583503,0.745038,0.701361,0.110426,0.582781,0.972909
3,0.021493,0.134411,0.599459,0.166666,0.335143,0.734784,0.135807,0.739456,0.396419,0.492639
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.716674,0.556082,0.465797,0.848366,0.105578

In [5]:
# Display last few values
my_df.tail()

,A,B,C,D,E,F,G,H,I,J
15,0.326433,0.721598,0.197161,0.280958,0.129487,0.566434,0.197363,0.829995,0.481920,0.948330
16,0.974002,0.800269,0.349325,0.680640,0.704014,0.688224,0.096507,0.701001,0.015671,0.135187
17,0.531291,0.646011,0.224935,0.556918,0.638876,0.286673,0.135122,0.395571,0.062288,0.967818
18,0.340485,0.678213,0.127507,0.329841,0.206992,0.988797,0.164046,0.670521,0.005501,0.116798
19,0.852272,0.179733,0.103616,0.215751,0.224524,0.873787,0.381192,0.439630,0.023006,0.110805

In [9]:
# My dataframe index structure
my_df.index

RangeIndex(start=0, stop=20, step=1)

In [10]:
# Selecting only columns names from my data
my_df.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object')

In [11]:
# To get my data values
my_df.values

array([[0.70722225, 0.20953657, 0.74390296, 0.31256365, 0.31758217,
        0.83939495, 0.20345008, 0.06803017, 0.42802913, 0.68306113],
       [0.39195422, 0.21202054, 0.09747753, 0.43635675, 0.8965188 ,
        0.08412436, 0.32712862, 0.98900027, 0.62726495, 0.57178613],
       [0.8024372 , 0.45099632, 0.82786433, 0.50901169, 0.58350294,
        0.74503788, 0.70136087, 0.1104261 , 0.58278122, 0.97290861],
       [0.02149314, 0.13441126, 0.59945911, 0.16666578, 0.33514341,
        0.73478361, 0.13580713, 0.73945575, 0.39641917, 0.49263941],
       [0.46517818, 0.3012182 , 0.4588392 , 0.38457782, 0.09333798,
        0.71667441, 0.55608222, 0.46579719, 0.84836627, 0.10557778],
       [0.2220734 , 0.76148748, 0.57892521, 0.96495698, 0.33081268,
        0.6846117 , 0.79279646, 0.04559299, 0.37728272, 0.99356542],
       [0.43503781, 0.32591766, 0.12003942, 0.16132963, 0.47879345,
        0.8868568 , 0.18571111, 0.16899329, 0.78036113, 0.67546105],
       [0.44219238, 0.37520437, 0.75764782, 0.32660721, 0.90410192,
        0.32587919, 0.90255565, 0.34928041, 0.62716408, 0.17055238],
       [0.1076721 , 0.67517209, 0.82752598, 0.53540667, 0.84310853,
        0.16407952, 0.13789739, 0.90933571, 0.04578917, 0.09812624],
       [0.16578224, 0.45021317, 0.38130073, 0.51467874, 0.28557009,
        0.05262212, 0.97744088, 0.9717161 , 0.05227402, 0.59111298],
       [0.28983399, 0.88763777, 0.40012577, 0.98774431, 0.11905429,
        0.20086734, 0.57616083, 0.54184866, 0.76488028, 0.37550867],
       [0.71490351, 0.32752439, 0.62120013, 0.69944826, 0.65110368,
        0.34622662, 0.82802681, 0.14101544, 0.4001606 , 0.43102817],
       [0.30095699, 0.14802769, 0.77752413, 0.28574765, 0.96953618,
        0.47822748, 0.7885753 , 0.38099641, 0.22234566, 0.40542292],
       [0.31702571, 0.87260032, 0.05240739, 0.57897358, 0.8168846 ,
        0.27745076, 0.80525659, 0.09049028, 0.47190885, 0.87215138],
       [0.14051764, 0.02888906, 0.22762115, 0.55386092, 0.77898238,
        0.64729374, 0.45030696, 0.44368207, 0.78480895, 0.02729882],
       [0.32643305, 0.721598  , 0.19716059, 0.28095786, 0.12948731,
        0.56643386, 0.19736302, 0.8299953 , 0.4819197 , 0.94832957],
       [0.97400205, 0.80026884, 0.34932489, 0.68064049, 0.7040142 ,
        0.68822387, 0.09650731, 0.70100146, 0.01567068, 0.13518709],
       [0.53129131, 0.64601069, 0.22493502, 0.55691827, 0.638876  ,
        0.28667321, 0.13512246, 0.3955713 , 0.06228763, 0.96781773],
       [0.34048452, 0.67821307, 0.12750724, 0.32984082, 0.206992  ,
        0.98879675, 0.16404645, 0.67052086, 0.00550103, 0.11679833],
       [0.85227229, 0.17973335, 0.10361635, 0.21575106, 0.2245242 ,
        0.87378677, 0.38119238, 0.43962958, 0.02300626, 0.11080521]])

In [12]:
# Summarising my data
my_df.describe()

,A,B,C,D,E,F,G,H,I,J
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,0.427438,0.459334,0.423720,0.474102,0.515396,0.529402,0.467139,0.472619,0.399911,0.487257
std,0.263518,0.273073,0.273835,0.233849,0.296289,0.290990,0.306510,0.312748,0.291478,0.341037
min,0.021493,0.028889,0.052407,0.161330,0.093338,0.052622,0.096507,0.045593,0.005501,0.027299
25%,0.272894,0.211400,0.179747,0.305860,0.270309,0.284368,0.180295,0.161999,0.059784,0.130590
50%,0.366219,0.412709,0.390713,0.472684,0.531148,0.606864,0.415750,0.441656,0.414095,0.461834
75%,0.575274,0.689059,0.651876,0.562432,0.788458,0.737347,0.789631,0.710615,0.627189,0.730334
max,0.974002,0.887638,0.827864,0.987744,0.969536,0.988797,0.977441,0.989000,0.848366,0.993565

In [17]:
# Sorting index of my data to descending
my_df.sort_index(axis=0, ascending=False)

,A,B,C,D,E,F,G,H,I,J
19,0.852272,0.179733,0.103616,0.215751,0.224524,0.873787,0.381192,0.439630,0.023006,0.110805
18,0.340485,0.678213,0.127507,0.329841,0.206992,0.988797,0.164046,0.670521,0.005501,0.116798
17,0.531291,0.646011,0.224935,0.556918,0.638876,0.286673,0.135122,0.395571,0.062288,0.967818
16,0.974002,0.800269,0.349325,0.680640,0.704014,0.688224,0.096507,0.701001,0.015671,0.135187
15,0.326433,0.721598,0.197161,0.280958,0.129487,0.566434,0.197363,0.829995,0.481920,0.948330
14,0.140518,0.028889,0.227621,0.553861,0.778982,0.647294,0.450307,0.443682,0.784809,0.027299
13,0.317026,0.872600,0.052407,0.578974,0.816885,0.277451,0.805257,0.090490,0.471909,0.872151
12,0.300957,0.148028,0.777524,0.285748,0.969536,0.478227,0.788575,0.380996,0.222346,0.405423
11,0.714904,0.327524,0.621200,0.699448,0.651104,0.346227,0.828027,0.141015,0.400161,0.431028
10,0.289834,0.887638,0.400126,0.987744,0.119054,0.200867,0.576161,0.541849,0.764880,0.375509
9,0.165782,0.450213,0.381301,0.514679,0.285570,0.052622,0.977441,0.971716,0.052274,0.591113
8,0.107672,0.675172,0.827526,0.535407,0.843109,0.164080,0.137897,0.909336,0.045789,0.098126
7,0.442192,0.375204,0.757648,0.326607,0.904102,0.325879,0.902556,0.349280,0.627164,0.170552
6,0.435038,0.325918,0.120039,0.161330,0.478793,0.886857,0.185711,0.168993,0.780361,0.675461
5,0.222073,0.761487,0.578925,0.964957,0.330813,0.684612,0.792796,0.045593,0.377283,0.993565
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.716674,0.556082,0.465797,0.848366,0.105578
3,0.021493,0.134411,0.599459,0.166666,0.335143,0.734784,0.135807,0.739456,0.396419,0.492639
2,0.802437,0.450996,0.827864,0.509012,0.583503,0.745038,0.701361,0.110426,0.582781,0.972909
1,0.391954,0.212021,0.097478,0.436357,0.896519,0.084124,0.327129,0.989000,0.627265,0.571786
0,0.707222,0.209537,0.743903,0.312564,0.317582,0.839395,0.203450,0.068030,0.428029,0.683061

In [18]:
# Sorting index of my data to ascending
my_df.sort_index(axis=0, ascending=True)

,A,B,C,D,E,F,G,H,I,J
0,0.707222,0.209537,0.743903,0.312564,0.317582,0.839395,0.203450,0.068030,0.428029,0.683061
1,0.391954,0.212021,0.097478,0.436357,0.896519,0.084124,0.327129,0.989000,0.627265,0.571786
2,0.802437,0.450996,0.827864,0.509012,0.583503,0.745038,0.701361,0.110426,0.582781,0.972909
3,0.021493,0.134411,0.599459,0.166666,0.335143,0.734784,0.135807,0.739456,0.396419,0.492639
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.716674,0.556082,0.465797,0.848366,0.105578
5,0.222073,0.761487,0.578925,0.964957,0.330813,0.684612,0.792796,0.045593,0.377283,0.993565
6,0.435038,0.325918,0.120039,0.161330,0.478793,0.886857,0.185711,0.168993,0.780361,0.675461
7,0.442192,0.375204,0.757648,0.326607,0.904102,0.325879,0.902556,0.349280,0.627164,0.170552
8,0.107672,0.675172,0.827526,0.535407,0.843109,0.164080,0.137897,0.909336,0.045789,0.098126
9,0.165782,0.450213,0.381301,0.514679,0.285570,0.052622,0.977441,0.971716,0.052274,0.591113
10,0.289834,0.887638,0.400126,0.987744,0.119054,0.200867,0.576161,0.541849,0.764880,0.375509
11,0.714904,0.327524,0.621200,0.699448,0.651104,0.346227,0.828027,0.141015,0.400161,0.431028
12,0.300957,0.148028,0.777524,0.285748,0.969536,0.478227,0.788575,0.380996,0.222346,0.405423
13,0.317026,0.872600,0.052407,0.578974,0.816885,0.277451,0.805257,0.090490,0.471909,0.872151
14,0.140518,0.028889,0.227621,0.553861,0.778982,0.647294,0.450307,0.443682,0.784809,0.027299
15,0.326433,0.721598,0.197161,0.280958,0.129487,0.566434,0.197363,0.829995,0.481920,0.948330
16,0.974002,0.800269,0.349325,0.680640,0.704014,0.688224,0.096507,0.701001,0.015671,0.135187
17,0.531291,0.646011,0.224935,0.556918,0.638876,0.286673,0.135122,0.395571,0.062288,0.967818
18,0.340485,0.678213,0.127507,0.329841,0.206992,0.988797,0.164046,0.670521,0.005501,0.116798
19,0.852272,0.179733,0.103616,0.215751,0.224524,0.873787,0.381192,0.439630,0.023006,0.110805

In [19]:
# Sorting by column
my_df.sort_values(by='J')

,A,B,C,D,E,F,G,H,I,J
14,0.140518,0.028889,0.227621,0.553861,0.778982,0.647294,0.450307,0.443682,0.784809,0.027299
8,0.107672,0.675172,0.827526,0.535407,0.843109,0.164080,0.137897,0.909336,0.045789,0.098126
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.716674,0.556082,0.465797,0.848366,0.105578
19,0.852272,0.179733,0.103616,0.215751,0.224524,0.873787,0.381192,0.439630,0.023006,0.110805
18,0.340485,0.678213,0.127507,0.329841,0.206992,0.988797,0.164046,0.670521,0.005501,0.116798
16,0.974002,0.800269,0.349325,0.680640,0.704014,0.688224,0.096507,0.701001,0.015671,0.135187
7,0.442192,0.375204,0.757648,0.326607,0.904102,0.325879,0.902556,0.349280,0.627164,0.170552
10,0.289834,0.887638,0.400126,0.987744,0.119054,0.200867,0.576161,0.541849,0.764880,0.375509
12,0.300957,0.148028,0.777524,0.285748,0.969536,0.478227,0.788575,0.380996,0.222346,0.405423
11,0.714904,0.327524,0.621200,0.699448,0.651104,0.346227,0.828027,0.141015,0.400161,0.431028
3,0.021493,0.134411,0.599459,0.166666,0.335143,0.734784,0.135807,0.739456,0.396419,0.492639
1,0.391954,0.212021,0.097478,0.436357,0.896519,0.084124,0.327129,0.989000,0.627265,0.571786
9,0.165782,0.450213,0.381301,0.514679,0.285570,0.052622,0.977441,0.971716,0.052274,0.591113
6,0.435038,0.325918,0.120039,0.161330,0.478793,0.886857,0.185711,0.168993,0.780361,0.675461
0,0.707222,0.209537,0.743903,0.312564,0.317582,0.839395,0.203450,0.068030,0.428029,0.683061
13,0.317026,0.872600,0.052407,0.578974,0.816885,0.277451,0.805257,0.090490,0.471909,0.872151
15,0.326433,0.721598,0.197161,0.280958,0.129487,0.566434,0.197363,0.829995,0.481920,0.948330
17,0.531291,0.646011,0.224935,0.556918,0.638876,0.286673,0.135122,0.395571,0.062288,0.967818
2,0.802437,0.450996,0.827864,0.509012,0.583503,0.745038,0.701361,0.110426,0.582781,0.972909
5,0.222073,0.761487,0.578925,0.964957,0.330813,0.684612,0.792796,0.045593,0.377283,0.993565

In [20]:
# Selecting columns
my_df['J']

0     0.683061
1     0.571786
2     0.972909
3     0.492639
4     0.105578
5     0.993565
6     0.675461
7     0.170552
8     0.098126
9     0.591113
10    0.375509
11    0.431028
12    0.405423
13    0.872151
14    0.027299
15    0.948330
16    0.135187
17    0.967818
18    0.116798
19    0.110805
Name: J, dtype: float64

In [21]:
# Selecting range of row
my_df[0:9]

,A,B,C,D,E,F,G,H,I,J
0,0.707222,0.209537,0.743903,0.312564,0.317582,0.839395,0.203450,0.068030,0.428029,0.683061
1,0.391954,0.212021,0.097478,0.436357,0.896519,0.084124,0.327129,0.989000,0.627265,0.571786
2,0.802437,0.450996,0.827864,0.509012,0.583503,0.745038,0.701361,0.110426,0.582781,0.972909
3,0.021493,0.134411,0.599459,0.166666,0.335143,0.734784,0.135807,0.739456,0.396419,0.492639
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.716674,0.556082,0.465797,0.848366,0.105578
5,0.222073,0.761487,0.578925,0.964957,0.330813,0.684612,0.792796,0.045593,0.377283,0.993565
6,0.435038,0.325918,0.120039,0.161330,0.478793,0.886857,0.185711,0.168993,0.780361,0.675461
7,0.442192,0.375204,0.757648,0.326607,0.904102,0.325879,0.902556,0.349280,0.627164,0.170552
8,0.107672,0.675172,0.827526,0.535407,0.843109,0.164080,0.137897,0.909336,0.045789,0.098126

In [22]:
# Selecting a specific row
my_df.loc[7]

A    0.442192
B    0.375204
C    0.757648
D    0.326607
E    0.904102
F    0.325879
G    0.902556
H    0.349280
I    0.627164
J    0.170552
Name: 7, dtype: float64

In [23]:
# Selecting a value from specific row and column
my_df.loc[4,['J']]

J    0.105578
Name: 4, dtype: float64

In [24]:
# Selecting all the rows from a column
my_df.loc[:,'D']

0     0.312564
1     0.436357
2     0.509012
3     0.166666
4     0.384578
5     0.964957
6     0.161330
7     0.326607
8     0.535407
9     0.514679
10    0.987744
11    0.699448
12    0.285748
13    0.578974
14    0.553861
15    0.280958
16    0.680640
17    0.556918
18    0.329841
19    0.215751
Name: D, dtype: float64

In [25]:
# Quicker way for selecting values from specific row and column
# Does not work for range
my_df.at[5, 'B']

0.7614874751101319

In [26]:
# Selecting data by its position
my_df.iloc[3]

A    0.021493
B    0.134411
C    0.599459
D    0.166666
E    0.335143
F    0.734784
G    0.135807
H    0.739456
I    0.396419
J    0.492639
Name: 3, dtype: float64

In [40]:
# Selecting data by condiction
my_df[my_df.A>0]

,A,B,C,D,E,F,G,H,I,J
0,0.707222,0.209537,0.743903,0.312564,0.317582,0.839395,0.203450,0.068030,0.428029,0.683061
1,0.391954,0.212021,0.097478,0.436357,0.896519,0.084124,0.327129,0.989000,0.627265,0.571786
2,0.802437,0.450996,0.827864,0.509012,0.583503,0.745038,0.701361,0.110426,0.582781,0.972909
3,0.021493,0.134411,0.599459,0.166666,0.335143,0.734784,0.135807,0.739456,0.396419,0.492639
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.716674,0.556082,0.465797,0.848366,0.105578
5,0.222073,0.761487,0.578925,0.964957,0.330813,0.684612,0.792796,0.045593,0.377283,0.993565
6,0.435038,0.325918,0.120039,0.161330,0.478793,0.886857,0.185711,0.168993,0.780361,0.675461
7,0.442192,0.375204,0.757648,0.326607,0.904102,0.325879,0.902556,0.349280,0.627164,0.170552
8,0.107672,0.675172,0.827526,0.535407,0.843109,0.164080,0.137897,0.909336,0.045789,0.098126
9,0.165782,0.450213,0.381301,0.514679,0.285570,0.052622,0.977441,0.971716,0.052274,0.591113
10,0.289834,0.887638,0.400126,0.987744,0.119054,0.200867,0.576161,0.541849,0.764880,0.375509
11,0.714904,0.327524,0.621200,0.699448,0.651104,0.346227,0.828027,0.141015,0.400161,0.431028
12,0.300957,0.148028,0.777524,0.285748,0.969536,0.478227,0.788575,0.380996,0.222346,0.405423
13,0.317026,0.872600,0.052407,0.578974,0.816885,0.277451,0.805257,0.090490,0.471909,0.872151
14,0.140518,0.028889,0.227621,0.553861,0.778982,0.647294,0.450307,0.443682,0.784809,0.027299
15,0.326433,0.721598,0.197161,0.280958,0.129487,0.566434,0.197363,0.829995,0.481920,0.948330
16,0.974002,0.800269,0.349325,0.680640,0.704014,0.688224,0.096507,0.701001,0.015671,0.135187
17,0.531291,0.646011,0.224935,0.556918,0.638876,0.286673,0.135122,0.395571,0.062288,0.967818
18,0.340485,0.678213,0.127507,0.329841,0.206992,0.988797,0.164046,0.670521,0.005501,0.116798
19,0.852272,0.179733,0.103616,0.215751,0.224524,0.873787,0.381192,0.439630,0.023006,0.110805

In [42]:
# Creating new data with missing values
my_new_df = my_df[my_df<.5]
print (my_new_df)

           A         B         C         D         E         F         G  \
0        NaN  0.209537       NaN  0.312564  0.317582       NaN  0.203450
1   0.391954  0.212021  0.097478  0.436357       NaN  0.084124  0.327129
2        NaN  0.450996       NaN       NaN       NaN       NaN       NaN
3   0.021493  0.134411       NaN  0.166666  0.335143       NaN  0.135807
4   0.465178  0.301218  0.458839  0.384578  0.093338       NaN       NaN
5   0.222073       NaN       NaN       NaN  0.330813       NaN       NaN
6   0.435038  0.325918  0.120039  0.161330  0.478793       NaN  0.185711
7   0.442192  0.375204       NaN  0.326607       NaN  0.325879       NaN
8   0.107672       NaN       NaN       NaN       NaN  0.164080  0.137897
9   0.165782  0.450213  0.381301       NaN  0.285570  0.052622       NaN
10  0.289834       NaN  0.400126       NaN  0.119054  0.200867       NaN
11       NaN  0.327524       NaN       NaN       NaN  0.346227       NaN
12  0.300957  0.148028       NaN  0.285748       NaN  0.478227       NaN
13  0.317026       NaN  0.052407       NaN       NaN  0.277451       NaN
14  0.140518  0.028889  0.227621       NaN       NaN       NaN  0.450307
15  0.326433       NaN  0.197161  0.280958  0.129487       NaN  0.197363
16       NaN       NaN  0.349325       NaN       NaN       NaN  0.096507
17       NaN       NaN  0.224935       NaN       NaN  0.286673  0.135122
18  0.340485       NaN  0.127507  0.329841  0.206992       NaN  0.164046
19       NaN  0.179733  0.103616  0.215751  0.224524       NaN  0.381192

           H         I         J
0   0.068030  0.428029       NaN
1        NaN       NaN       NaN
2   0.110426       NaN       NaN
3        NaN  0.396419  0.492639
4   0.465797       NaN  0.105578
5   0.045593  0.377283       NaN
6   0.168993       NaN       NaN
7   0.349280       NaN  0.170552
8        NaN  0.045789  0.098126
9        NaN  0.052274       NaN
10       NaN       NaN  0.375509
11  0.141015  0.400161  0.431028
12  0.380996  0.222346  0.405423
13  0.090490  0.471909       NaN
14  0.443682       NaN  0.027299
15       NaN  0.481920       NaN
16       NaN  0.015671  0.135187
17  0.395571  0.062288       NaN
18       NaN  0.005501  0.116798
19  0.439630  0.023006  0.110805

In [43]:
# Drop all empty rows
my_new_df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E, F, G, H, I, J]
Index: []

In [44]:
# Replace within values with "1"
my_new_df.fillna(value=1)

,A,B,C,D,E,F,G,H,I,J
0,1.000000,0.209537,1.000000,0.312564,0.317582,1.000000,0.203450,0.068030,0.428029,1.000000
1,0.391954,0.212021,0.097478,0.436357,1.000000,0.084124,0.327129,1.000000,1.000000,1.000000
2,1.000000,0.450996,1.000000,1.000000,1.000000,1.000000,1.000000,0.110426,1.000000,1.000000
3,0.021493,0.134411,1.000000,0.166666,0.335143,1.000000,0.135807,1.000000,0.396419,0.492639
4,0.465178,0.301218,0.458839,0.384578,0.093338,1.000000,1.000000,0.465797,1.000000,0.105578
5,0.222073,1.000000,1.000000,1.000000,0.330813,1.000000,1.000000,0.045593,0.377283,1.000000
6,0.435038,0.325918,0.120039,0.161330,0.478793,1.000000,0.185711,0.168993,1.000000,1.000000
7,0.442192,0.375204,1.000000,0.326607,1.000000,0.325879,1.000000,0.349280,1.000000,0.170552
8,0.107672,1.000000,1.000000,1.000000,1.000000,0.164080,0.137897,1.000000,0.045789,0.098126
9,0.165782,0.450213,0.381301,1.000000,0.285570,0.052622,1.000000,1.000000,0.052274,1.000000
10,0.289834,1.000000,0.400126,1.000000,0.119054,0.200867,1.000000,1.000000,1.000000,0.375509
11,1.000000,0.327524,1.000000,1.000000,1.000000,0.346227,1.000000,0.141015,0.400161,0.431028
12,0.300957,0.148028,1.000000,0.285748,1.000000,0.478227,1.000000,0.380996,0.222346,0.405423
13,0.317026,1.000000,0.052407,1.000000,1.000000,0.277451,1.000000,0.090490,0.471909,1.000000
14,0.140518,0.028889,0.227621,1.000000,1.000000,1.000000,0.450307,0.443682,1.000000,0.027299
15,0.326433,1.000000,0.197161,0.280958,0.129487,1.000000,0.197363,1.000000,0.481920,1.000000
16,1.000000,1.000000,0.349325,1.000000,1.000000,1.000000,0.096507,1.000000,0.015671,0.135187
17,1.000000,1.000000,0.224935,1.000000,1.000000,0.286673,0.135122,0.395571,0.062288,1.000000
18,0.340485,1.000000,0.127507,0.329841,0.206992,1.000000,0.164046,1.000000,0.005501,0.116798
19,1.000000,0.179733,0.103616,0.215751,0.224524,1.000000,0.381192,0.439630,0.023006,0.110805

In [45]:
# Getting my data mean
my_mean = my_new_df.mean()
my_mean

A    0.283331
B    0.261974
C    0.228363
D    0.290040
E    0.252130
F    0.246239
G    0.219503
H    0.258292
I    0.229430
J    0.224450
dtype: float64

In [46]:
# Replace empty values with mean value
my_new_df.fillna(value=my_mean)

,A,B,C,D,E,F,G,H,I,J
0,0.283331,0.209537,0.228363,0.312564,0.317582,0.246239,0.203450,0.068030,0.428029,0.224450
1,0.391954,0.212021,0.097478,0.436357,0.252130,0.084124,0.327129,0.258292,0.229430,0.224450
2,0.283331,0.450996,0.228363,0.290040,0.252130,0.246239,0.219503,0.110426,0.229430,0.224450
3,0.021493,0.134411,0.228363,0.166666,0.335143,0.246239,0.135807,0.258292,0.396419,0.492639
4,0.465178,0.301218,0.458839,0.384578,0.093338,0.246239,0.219503,0.465797,0.229430,0.105578
5,0.222073,0.261974,0.228363,0.290040,0.330813,0.246239,0.219503,0.045593,0.377283,0.224450
6,0.435038,0.325918,0.120039,0.161330,0.478793,0.246239,0.185711,0.168993,0.229430,0.224450
7,0.442192,0.375204,0.228363,0.326607,0.252130,0.325879,0.219503,0.349280,0.229430,0.170552
8,0.107672,0.261974,0.228363,0.290040,0.252130,0.164080,0.137897,0.258292,0.045789,0.098126
9,0.165782,0.450213,0.381301,0.290040,0.285570,0.052622,0.219503,0.258292,0.052274,0.224450
10,0.289834,0.261974,0.400126,0.290040,0.119054,0.200867,0.219503,0.258292,0.229430,0.375509
11,0.283331,0.327524,0.228363,0.290040,0.252130,0.346227,0.219503,0.141015,0.400161,0.431028
12,0.300957,0.148028,0.228363,0.285748,0.252130,0.478227,0.219503,0.380996,0.222346,0.405423
13,0.317026,0.261974,0.052407,0.290040,0.252130,0.277451,0.219503,0.090490,0.471909,0.224450
14,0.140518,0.028889,0.227621,0.290040,0.252130,0.246239,0.450307,0.443682,0.229430,0.027299
15,0.326433,0.261974,0.197161,0.280958,0.129487,0.246239,0.197363,0.258292,0.481920,0.224450
16,0.283331,0.261974,0.349325,0.290040,0.252130,0.246239,0.096507,0.258292,0.015671,0.135187
17,0.283331,0.261974,0.224935,0.290040,0.252130,0.286673,0.135122,0.395571,0.062288,0.224450
18,0.340485,0.261974,0.127507,0.329841,0.206992,0.246239,0.164046,0.258292,0.005501,0.116798
19,0.283331,0.179733,0.103616,0.215751,0.224524,0.246239,0.381192,0.439630,0.023006,0.110805